##### DEPENDENCIES
FROM --platform=linux/amd64 node:20-alpine3.18 AS deps
RUN apk add --no-cache libc6-compat openssl1.1-compat
RUN apk update && apk add ffmpeg
WORKDIR /app

# Install Prisma Client
COPY server/prisma ./

# Install dependencies based on the preferred package manager
COPY server/package.json server/package-lock.json ./
RUN chmod -R a+rX /app
RUN npm ci

# Rebuild the source code only when needed
FROM deps AS builder
LABEL stage=builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY server .
RUN chmod -R a+rX /app

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
ENV NEXT_TELEMETRY_DISABLED 1
ENV DOCKER_NETWORK "build"
ENV DATABASE_URL "build"
ENV URL "build"
ENV OAUTH_CLIENT_ID "build"
ENV OAUTH_CLIENT_SECRET "build"

RUN npm run build

# Production image, copy all the files and run next
FROM deps AS runner
LABEL stage=runner
WORKDIR /app

# Uncomment the following line in case you want to disable telemetry during runtime.
ENV NEXT_TELEMETRY_DISABLED 1
ENV NODE_ENV production

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/next.config.mjs ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/package.json ./package.json

RUN npm install --omit=dev

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/dist ./dist
COPY --from=builder --chown=nextjs:nodejs /app/.next ./.next
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs
EXPOSE 3000
ENV PORT 3000

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD ["npm", "run", "deploy"]