name: handzone
version: "3.9"
services:
  db:
    image: postgres:16.2
    restart: always
    container_name: handzone-db
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_DB: handzone

  docker:
    image: tecnativa/docker-socket-proxy
    privileged: true
    environment:
      - CONTAINERS=1
      - ALLOW_START=1
      - ALLOW_STOP=1
      - ALLOW_RESTART=1
      - POST=1
    restart: always
    container_name: handzone-docker
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
  
  nginx:
    image: nginx:latest
    restart: always
    container_name: handzone-nginx
    ports:
      - "80:80"
      - "443:443"
      - "5900:5900"
    volumes:
      - type: bind
        source: ./.nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      - type: bind
        source: ./.nginx/certs
        target: /etc/ssl/certs/

  app-dev:
    build:
      context: .
      dockerfile: dockerfile-dev
    env_file:
      - .env
    restart: always
    container_name: handzone-dev
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      DATABASE_URL: "postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db/handzone?schema=public"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    depends_on:
      - db
      - docker

    # Ensure DB schema exists before starting dev server
    command: >-
      sh -c "
      (npx prisma generate || true) &&
      until npx prisma migrate deploy; do echo 'Waiting for database...'; sleep 2; done &&
      ./node_modules/.bin/tsx src/server/index.ts
      "

networks:
  default:
    name: ${DOCKER_NETWORK}

volumes:
  database:
